### ISSUE TITLE
Built-in timers/intervals

### ISSUE THREAD

**Issue by mcginty** [tonarino/actor#14]
Do we want??

**Comment by bschwind** [comment]
Some resources that will be helpful here:

https://github.com/tokio-rs/tokio/tree/master/tokio-util/src/time

https://crates.io/crates/hierarchical_hash_wheel_timer

**Comment by bschwind** [comment]
A simple, naive implementation has been implemented in #52 but I'd like to eventually replace that implementation with #53 after settling on a user-facing API.

**Comment by strohel** [comment]
#53 has been merged, but per comments therein we still want to introduce a helper actor + an ergonomic API on top of it. I'll open a PR to iterate that.
